name: Skip Workflow - Push To Main
#skip2
on:
  push:
    branches:
    - main

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    
    runs-on: ubuntu-latest

    steps:
      - name: Build The Code
        run: |
          echo "Build The Code"
      
  
